html/backend/controllers/CatalogController.php
<?php

namespace backend\controllers;

use Yii;
use yz\shoppingcart\ShoppingCart;
use common\models\Product;
use backend\models\ProductSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\imagine\Image;
use Imagine\Image\Box;
use yii\filters\AccessControl;
use common\models\FoodCategories;
use common\models\FoodcategoryProducts;
use common\models\Userfoodcategory;
use common\models\ProductOption;
use yii\db\Query;
use yii\helpers\ArrayHelper;
/**
 * CatalogController implements for Product model.
 */
class CatalogController extends Controller
{
    /* public function behaviors()
    {
      
            $behaviors['access'] = [
                'class' => AccessControl::className(),
                'rules' => [
                    [                       
                       'allow' => true,
                       'roles' => ['@'],
                       'matchCallback' => function ($rule, $action) {						    
                        $module = Yii::$app->controller->module->id;                     
                        $action = Yii::$app->controller->action->id;                         
                        $controller = Yii::$app	->controller->id;                        
                        $route = "$controller/$action";                                                    	
                        $post = Yii::$app->request->post();
                        if(\Yii::$app->user->can($route)){
							return true;
						}
                         
                        } 
                   
                    ],
                ],
            ];
            return $behaviors;
	}*/
	
	public function actions()
	{
		return [
			'uploadPhoto' => [
				'class' => 'paras\cropper\actions\UploadAction',
				'url' => Yii::$app->urlManagerFrontEnd->createAbsoluteUrl(['uploads/catalog/']),
				'path' => '@frontend/web/uploads/catalog/',
			]
		];
	}

    /**
     * Lists all Product models data.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Regions model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
		$catTree	=	FoodcategoryProducts::find()->select('category_id,name')
										->joinWith('foodcategories',false)
										->where(['product_id'=>$id])
										->asArray()->all();
				$catTree	=	ArrayHelper::map($catTree,'category_id','name');
		  return $this->render('view', [
            'model' => $this->findModel($id),
			'optionVal' => $this->getOptionVal($id),
			'categoryTree'=>$catTree,
        ]);
    }

    /**
     * Creates a new Regions model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Product();
        $model->scenario = 'create';  
		$FoodcategoryProducts = new FoodcategoryProducts();		
		 if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$cateTreeVal = Yii::$app->request->post('categoryTree');
			$model->category = !empty($cateTreeVal)?implode(',',$cateTreeVal): '0';
			/* upload product image  */
			   
						if ($model->pimage) {
						
						$path = parse_url($model->pimage, PHP_URL_PATH);						
						$model->image=basename($path);
						
						$thumbimage=Yii::$app->params['productPath'].'thumb/'.$model->image;
						//print_r($thumbimage);die;
						Image::getImagine()
						->open($model->pimage)
						->thumbnail(new Box(100,100))
						->save($thumbimage);
					}
					$model->save(false);
				/* save custom option ingredients  */
					$options 		= Yii::$app->request->post('Product');
					if(!empty($options['title'][0]) && !empty($options['oprice'])){			
						$match = array();						
						$i=0;
						$_price = $options['oprice'];
						$isIncluded 	= $options['is_included'];
						foreach($options['title'] as $_product)
						{
							if($_product){
								$data = array();
								$data['product_id'] = $model->id;
								$data['title'] = $_product;
								$data['price'] = $_price[$i]==0 ? 0.00: $_price[$i];
								$data['is_included'] = $isIncluded[$i]==0?0:1;
								$match[] = $data;
							}
							$i++;
						}
							
							$column=['product_id','title','price','is_included'];
							Yii::$app->db->createCommand()->batchInsert(ProductOption::tableName(),$column,$match)->execute();
						
					} //if(!empty($options['title']) && !empty($options['oprice']))
					/*save category items */	
								
					if(!empty($cateTreeVal)){						
						$rows = array();
						foreach($cateTreeVal as $_cateTreeVal){
							$rows[] = [
							'product_id'=>$model->id,
							'category_id' => $_cateTreeVal,
							'status' => 1,
							'created_at' => time(),
							'updated_at' => time()							
							];
						}
						$columnNameArray=['product_id','category_id','status','created_at','updated_at'];
						Yii::$app->db->createCommand()->batchInsert(FoodcategoryProducts::tableName(),$columnNameArray, $rows)->execute();
					}
						
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
				'categoryTree' => $this->getCategoryTree(0,0),
	     ]);
        }
    }

    /**
     * Updates an existing Regions model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
		$FoodcategoryProducts = new FoodcategoryProducts();
		$pOptionModel = $this->findModelpOption(array('product_id'=>$id));
		if ($model->load(Yii::$app->request->post()) && $model->validate()) {		
			$cateTreeVal = Yii::$app->request->post('categoryTree');
			$model->category = $cateTreeVal!=''?implode(',',$cateTreeVal): '';
			/* chanage product image */						
			if ($model->pimage) {
					
				$uniqueName = $model->sku.substr(md5(date("Ymdhis")),0,15).'.'.$model->pimage;
				
						if(strstr($model->image,".")) {							
							$oldImage = explode(".",$model->image); 
							
						}else { 
							$oldImage[0] = $uniqueName;
						}
						if ($model->pimage) {
								$path = parse_url($model->pimage, PHP_URL_PATH);						
						$model->image=basename($path);
						
						$thumbimage=Yii::$app->params['productPath'].'thumb/'.$model->image;
						//print_r($thumbimage);die;
						Image::getImagine()
						->open($model->pimage)
						->thumbnail(new Box(100,100))
						->save($thumbimage);
					}
        		
        			
          	 }          	
          	 $model->save(false);
			/* save custom option ingredients  */
				$options 		= Yii::$app->request->post('Product');				
				if(!empty($options['title']) && !empty($options['oprice'])){
					$existingOpVal  = $this->getOptionVal($id);					
						$match = array();
						$i=0;
						$_price 		= $options['oprice'];
						$isIncluded 	= $options['is_included'];
						foreach($options['title'] as $_product)
						{						
							if($_product){
								$data = array();
								$data['product_id'] = $id;
								$data['title'] = $_product;
								$data['price'] = $_price[$i];
								$data['is_included'] = $isIncluded[$i]==0?0:1;
								$match[] = $data;
							}
							$i++;
						}					
						$ifdefference = $match==$existingOpVal;							
						if($ifdefference== false) { 
							$ip= 0;
							if(isset($match)){
								ProductOption::deleteAll('product_id ='.$id);
								$column=['product_id','title','price','is_included'];
								Yii::$app->db->createCommand()->batchInsert(ProductOption::tableName(),$column,$match)->execute();
							} //if(($optionTitle) && ($oPrice))
						} //if($ifdefference== true) 
				} //if(!empty($options['title']) && !empty($options['oprice'])){
			/*save categories in database */
			$cateTreeVal = Yii::$app->request->post('categoryTree');
			if(!empty($cateTreeVal)){				
				$rows = array();
				foreach($cateTreeVal as $_cateTreeVal){
					$rows[] = [
						'product_id'=>$model->id,
						'category_id' => $_cateTreeVal,
						'status' => 1,
						'created_at' => time(),
						'updated_at' => time()							
					];
				}
				FoodcategoryProducts::deleteAll('product_id ='.$model->id);
				$columnNameArray =['product_id','category_id','status','created_at','updated_at'];
				Yii::$app->db->createCommand()->batchInsert(FoodcategoryProducts::tableName(),$columnNameArray, $rows)->execute();	
			}
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
				'categoryTree' => $this->getCategoryTree($model->store_id,$model->id),
				'optionVal' => $this->getOptionVal($id),
            ]);
        }
    }
	public function getOptionVal($pId){
		return ProductOption::find()->select(['product_id','title','price','is_included'])->where('product_id='.$pId)->asArray()->all();
		
	}
  protected function findModelpOption($id)
    {
        	if (($pOption = ProductOption::findOne(['product_id'=>$id])) !== null) { 
        	
            return $pOption;
        } else {
            return true;
        }
    }
    /**
     * Deletes an existing Regions model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        ProductOption::deleteAll('product_id ='.$id);
        return $this->redirect(['index']);
    }
    
    /* delete via ajax */   
	public function actionDeletebyajax()  
	{
		$pid = $_POST['id'];  
		if($pid) {

html/backend/views/catalog/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\RegionsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="regions-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'region') ?>

    <?= $form->field($model, 'region_code') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app','Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app','Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

html/backend/views/catalog/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Region */

$this->title = Yii::t('app','Create Catalogue Item');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app','Product'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>


<section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- general form elements -->
              <div class=" panel panel-primary">
                <div class="panel-heading">    
                    <div class="pull-right">                       
                    </div>
                    <!-- Header Title-->
                    <h3 class="panel-title">
                        <i class="glyphicon glyphicon-plus"></i>  <?= Html::encode($this->title) ?>
                    </h3>
                    <!-- Header Title end -->
                    <div class="clearfix"></div>
                </div>
			<div class="panel-before" >  
				  
				<div class="row">
				<div class="col-sm-10 col-md-10 col-lg-10">
					<h4 class="bg-info">Add products to the catalogue to enable them to be sold in-app. Catalogue Items you add will be sold through deals. Menu items you add will be sold through the FOOD MENU button on the store page.
				  </h4>
				</div>
				<div class="col-sm-2" style="margin-top:12px;">
					 <div role="toolbar" class="btn-toolbar kv-grid-toolbar">
						<div class="btn-group"><a title="<?= Yii::t('app','All Products') ?>" href="<?=Yii::$app->urlManager->createUrl(['catalog/index',])?>" class="btn btn-primary"><i class="glyphicon glyphicon-list"></i></a> 
						<a data-pjax="0" title="<?= Yii::t('app','Reset Grid') ?>" href="<?=Yii::$app->urlManager->createUrl(['catalog/create',])?>" class="btn btn-default"><i class="glyphicon glyphicon-repeat"></i></a></div>
					</div>    
				</div>
				
				<div class="clearfix"></div>
				
			</div>
			</div>

                
                
                <!-- form start -->
                
                 <?= $this->render('_form', [
			'model' => $model,
			'categoryTree' =>$categoryTree,
    ]) ?>
              
              </div><!-- /.box -->
            </div><!--/.col (right) -->
          </div>   <!-- /.row -->
        </section>

html/backend/views/catalog/index.php
<?php

use yii\helpers\Html;
#use yii\grid\GridView;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use backend\models\Usermanagement;
/* @var $this yii\web\View */
/* @var $searchModel app\models\RegionsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app','Catalogue');
$this->params['breadcrumbs'][] = $this->title;
$userType=Yii::$app->user->identity->user_type;
$visiable = 0;
if($userType==1){
$partners = ArrayHelper::map(Usermanagement::find()->where(['user_type' => 7])->orderBy('orgName ASC')->groupBy('orgName')->all(), 'id', 'orgName');
$visiable = 1;
}else{
		$partners='';
	}
?>
<div class="catalog-index">


<?php

        echo GridView::widget([
        'dataProvider'=>$dataProvider,
        'filterModel'=>$searchModel,
                'rowOptions' => function ($model, $key, $index, $grid) {
    return ['id' => $model['id']];
},
        'columns'=>  [
        
            'name',
            'sku',            
           
            [
            'attribute'=>'price',
            'value'=>'priceval',
            ],
            [
            'attribute'=>'image',
            'value'=>'thumbimage',
            'format' => ['image',['width'=>'75','height'=>'75']],
            ],
            
            [
            'attribute'=>'status',
            'value'=>'statustype',
             'filter' => array('1' => Yii::t('app','Enable'), '0' => Yii::t('app','Disable') ),
            ],
			 [
				'attribute'=>'p_type',
				'value'=>'ptype',
				'filter' => array('1' => Yii::t('app','Simple'), '2' => Yii::t('app','FoodOrder-Simple'),'3'=>Yii::t('app','FoodOrder-Group') ),
            ],

          [
				'label' => Yii::t('app','Advertiser'),
				'attribute'=>Yii::t('app','store_id'),           			
				'value'=> 'partnernameval',    
				'visible'=> $visiable,
                'filterType'=>GridView::FILTER_SELECT2,
                'filterWidgetOptions' => [			
				'data' => $partners,
				'size' => Select2::SMALL,
				'options' => ['placeholder' => Yii::t('app','Select partner')],
				'pluginOptions' => [					
					'width'=>'150px',
					'allowClear' => true,
				],
					

            ],
            ],
            
           ['class'=>'kartik\grid\ActionColumn'],
            ],
        'containerOptions'=>['style'=>'overflow: auto'], // only set when $responsive = false
        'headerRowOptions'=>['class'=>'kartik-sheet-style'],
        'filterRowOptions'=>['class'=>'kartik-sheet-style'],
        'pjax'=>true, // pjax is set to always true for this demo
      //   'export'=>false,       
        'beforeHeader'=>[
            [
                /*'columns'=>[
                    ['content'=>'Header Before 1', 'options'=>['colspan'=>5, 'class'=>'text-center warning']], 
                    ['content'=>'Header Before 2', 'options'=>['colspan'=>3, 'class'=>'text-center warning']], 
                    ['content'=>'Header Before 3', 'options'=>['colspan'=>3, 'class'=>'text-center warning']], 
                ],*/
                'options'=>['class'=>'skip-export'] // remove this row from export
            ]
        ],
        // set your toolbar
        'toolbar'=> [
            ['content'=>
                Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'],[ 'title'=>Yii::t('app','Create Catalogue Item '),'data-pjax'=>1, 'class'=>'btn btn-success', ]) . ' '.
                Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], ['data-pjax'=>0, 'class'=>'btn btn-default', 'title'=> Yii::t('app','Reset Grid')])
            ],
            '{export}',
            '{toggleData}',
        ],
        // set export properties
       'export'=>[
            'fontAwesome'=>true
        ],
        // parameters from the demo form
        'bordered'=>true,
       'striped'=>false,
        'condensed'=>true,
        'responsive'=>true,
        'hover'=>true,
        'showPageSummary'=>true,
        'panel'=>[
            'type'=>GridView::TYPE_PRIMARY,
            'heading'=>'<i class="glyphicon glyphicon-list"></i>'. Yii::t('app','  Catalogue'),
        ],
        'persistResize'=>false,
        'exportConfig'=>['csv'=>'csv'],
    ]);
    

?>
 
</div>

html/backend/views/catalog/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Product */

$this->title = Yii::t('app','Update Product: ') . ' ' . ucfirst($model->name);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app','Products'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => ucfirst($model->name), 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app','Update');
?>
    <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- general form elements -->
               <div class=" panel panel-primary">
                <div class="panel-heading">    
                    <div class="pull-right">                       
                    </div>
                    <!-- Header Title-->
                    <h3 class="panel-title">
                        <i class="glyphicon glyphicon-user"></i>  <?= Html::encode($this->title) ?>
                    </h3>
                    <!-- Header Title end -->
                    <div class="clearfix"></div>
                </div>
                <!-- form start -->
                
                 <?= $this->render('_form', [
        'model' => $model,
		'categoryTree' =>$categoryTree,
		'optionVal' =>$optionVal,
    ]) ?>
              
              </div><!-- /.box -->
            </div><!--/.col (right) -->
          </div>   <!-- /.row -->

html/backend/views/catalog/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Product */

 
 
$this->title = Yii::t('app','View Product: ') . ' ' .ucfirst($model->name);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app','Products'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$userType=Yii::$app->user->identity->user_type;
$visible = 0;
if($userType==1){
$visible = 1;
}
else{
	$visiable = 0;
}

?>
    <div class="row">
            <!-- left column -->
          
             <div class="col-md-12">
            <div class=" panel panel-primary">
                <div class="panel-heading">    
                    <div class="pull-right">                       
                    </div>
                    <!-- Header Title-->
                    <h3 class="panel-title">
                        <i class="glyphicon glyphicon-user"></i>  <?= Html::encode($this->title) ?>
                    </h3>
                    <!-- Header Title end -->
                    <div class="clearfix"></div>
                </div>
              <!-- general form elements -->
            
                <div class="box-header with-border">
                  <h3 class="box-title"> <!--<?= Html::encode($this->title) ?>--> </h3>
              <p>   
             <?= Html::a(Yii::t('app','Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
     		   <?= Html::a(Yii::t('app','Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app','Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
         <?= Html::a(Yii::t('app','OK'), ['index', 'id' => $model->id], ['class' => 'btn bg-green']) ?>
           </p>
        
                </div><!-- /.box-header -->
                <!-- form start -->

 <div class="table-responsive">
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            /*['attribute' => 'Store Name',
				'visible'=>$visible,
			   'value' => $model->partnernameval,          
            ],*/
            ['attribute' => 'Partner Name',
				'visible'=>$visible,
			   'value' => $model->partnernameval,          
            ],
            'name',
            'sku',            
            'description',
            'urlkey',
			        
			 ['attribute' => 'Price',
			   'value' => $model->priceval             
             ],          
            
             ['attribute' => 'Is online',
			   'value' => $model->onlinestatus             
             ],
           
			 ['attribute' => 'Status',
              'value' => $model->statustype            
             ],
              [                     
            'label' => Yii::t('app','Categories'),
            'value' => implode(",",$categoryTree),
             ],
            
             [
				'attribute'=>'Product image',
				'value'=>   $model->thumbimage,
				'format' => ['image',['width'=>'100','height'=>'100']],
			 ],

        ],
    ]) ?>
    </div>
	<?php if($model->has_option==1 && isset($optionVal)) { ?>
		<div class="box box-success">
			<div class="box-header">
					  <i class="fa fa-check"></i>

					  <h4 class="box-title"><?= Yii::t('app','Ingredient/Options') ?></h4>
			</div>
		   <table class="table table-striped table-bordered detail-view">
			<tbody>
			<tr><th>Title</th><th><?= Yii::t('app','Price') ?></th></tr>
			<?php foreach($optionVal as $_optionVal){ 	?>
				<tr>
					<td><?php echo $_optionVal['title']; ?></td>
					<td><?php echo $_optionVal['price']; ?>	</td>
				</tr>
			<?php } ?>
			</tbody>
		</table>
		</div>
	<?php } //if($model->has_option==1) ?>
</div><!-- /.box -->

            </div><!--/.col (right) -->
          </div>   <!-- /.row -->