html/backend/controllers/BeaconmanagerController.php
<?php

namespace backend\controllers;

use Yii;
use yii\base\Model;
use common\models\Beaconmanager;
use common\models\Store;
use backend\models\BeaconmanagerSearch;
use backend\models\Storebeacons;
use backend\models\Beacongroup;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\db\Query;

/**
 * BeaconManagerController implements for BeaconManager model.
 */
class BeaconmanagerController extends Controller
{
    public function behaviors()
    {
      
            $behaviors['access'] = [
                'class' => AccessControl::className(),
                'rules' => [
                    [                       
                       'allow' => true,
                       'roles' => ['@'],
                       'matchCallback' => function ($rule, $action) {						    
                        $module = Yii::$app->controller->module->id;                     
                        $action = Yii::$app->controller->action->id;                         
                        $controller = Yii::$app	->controller->id;                        
                        $route = "$controller/$action";                                                    	
                        $post = Yii::$app->request->post();
                        if(\Yii::$app->user->can($route)){
							return true;
						}
                         
                        } 
                   
                    ],
                ],
            ];
            return $behaviors;
	}

    /**
     * Lists all Beaconmanager models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BeaconmanagerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Beaconmanager model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Beaconmanager model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Beaconmanager();
		$storebeacon = new Storebeacons();
        
        if ($model->load(Yii::$app->request->post()) && $storebeacon->load(Yii::$app->request->post()) && Model::validateMultiple([$model, $storebeacon])) {			
			          	
          if(is_array($model->groups)){
			$beaconid = implode(', ',$_POST['BeaconManager']['groups']);
			$str = rtrim($beaconid,',');			
			$model->groups = $str;   }		
			
			
				$model->save(false);
					$data = [];
					
					if($storebeacon->store_id) {
					
						$data[] = ['beacon_id' => $model->id, 'store_id' => $storebeacon->store_id, 'status' => $model->status];
					
					
						Yii::$app->db->createCommand()->batchInsert(
						Storebeacons::tableName(), 
						['beacon_id', 'store_id', 'status'], 
						$data
						)->execute();
			        }
			
			
          	 
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'storebeacon' => $storebeacon,
            ]);
        }
    }

    /**
     * Updates an existing Beaconmanager model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
		
        $model = $this->findModel($id);
     
        $storebeacon = $this->findbeaconstoreModel($id);        
        $storeBeaconModel= new Storebeacons();
        $storeBeaconModel->store_id= $storebeacon;
         

        if ($model->load(Yii::$app->request->post()) && $storeBeaconModel->load(Yii::$app->request->post()) && Model::validateMultiple([$model, $storeBeaconModel])) {
				
			$model->imageFile = UploadedFile::getInstance($model, 'imageFile');
			
			$uniqueimage = substr(md5(date("Ymdhis")),0,15); 
 			/* get old file name */
 			if(isset($model->imgBeaconLoc) && $model->imgBeaconLoc !='') {
			$oldimage = explode("/",$model->imgBeaconLoc);  $oldImageName = explode(".",$oldimage[1]); 
			}else { 
				$oldImageName[0] = $uniqueimage;
			}
        
            /* save image */
        	if ($model->imageFile) {
  	     	 		$imageName = $oldImageName[0];
        			$model->imgBeaconLoc = 'uploads/'.$imageName.'.'.$model->imageFile->extension;
       			
        			$model->imageFile->saveAs('uploads/'.$imageName.'.'.$model->imageFile->extension);
          	 }
          	 /* update multiple beacon */
			if(is_array($model->groups)){
			$beaconid = implode(', ',$_POST['BeaconManager']['groups']);
			$str = rtrim($beaconid,',');			
			$model->groups = $str;  	 }
			
			$model->locationOwnerID = Yii::$app->request->post()['BeaconManager']['locationOwnerID'];
			//$model->locationBrockerID = Yii::$app->request->post()['BeaconManager']['locationBrockerID'];
			//$model->intervalID = Yii::$app->request->post()['BeaconManager']['intervalID'];
			
			$model->save(false);  //  save all data in model
			
			
		       	     if($storeBeaconModel->store_id){
							Storebeacons::deleteAll('beacon_id ='.$id);
							
							$storeBeaconModel->store_id = $storeBeaconModel->store_id;
							$storeBeaconModel->beacon_id = $model->id;
							$storeBeaconModel->status = $model->status;
							$storeBeaconModel->save(false);
											
						}
											
					
						
						
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'storebeacon' => $storebeacon,
				'storeBeaconModel' => $storeBeaconModel,
            ]);
        }
    }

    /**
     * Deletes an existing Beaconmanager model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
		 Storebeacons::deleteAll('beacon_id ='.$id);
        return $this->redirect(['index']);
    }
    
    /* delete via ajax */   
	public function actionDeletebyajax()  
	{
		$pid = $_POST['id'];  		
		if($pid) {
			$this->findModel($pid)->delete();
			Storebeacons::deleteAll('beacon_id ='.$pid);
			echo $pid; exit;
		}
	}
	
	public function actionStorelist()  
	{
	
	$partnerID = $_POST['id'];  
		if($partnerID) {
						 
			 $storebeaconlist =  ArrayHelper::map(Store::find()
				->joinWith('storebeacons', true, 'LEFT JOIN')
				->select('tbl_store_beacons.beacon_id ,tbl_store_beacons.store_id ,tbl_store.id,tbl_store.storename,tbl_store.status')
				->Where([Store::tableName().'.status'=>1, Store::tableName().'.owner'=>$partnerID, ])
			//	->andWhere('store_id IS NULL' )				
				->all(), 'id', 'storename');
				
			$st = array('data'=> $storebeaconlist);
			echo json_encode($st); exit;
		}
	
	}	
	
			public function actionBeaconGroupname() {
			$data=Yii::$app->request->post();
			
			$q = $data['q'];
			
			#$sq = is_array($data['sq'])?array_reverse($data['sq']):'';
			#$sq = is_array($sq)?array_shift($sq):'';
			$data['sq'] = is_array($data['sq'])?$data['sq']:'';
						
			$id = null;
		\Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
			$out = ['results' => ['id' => '', 'text' => '']];
			if (!is_null($q)) {
				$query = new Query;
				$query->select('id, group_name AS text')
								->from('tbl_beacon_group')
								->where(['like','group_name', $q])->andWhere(['status' =>1]);
								
				if(is_array($data['sq'])){
					$beaconDetail =   Beacongroup::find()->where('id IN('.implode(',',$data['sq']).')')->all();
					$alreadyState=false;
					foreach($beaconDetail as $beaconType){					
						
				
					
						if($beaconType["type"]==1){								
								$query->andwhere(["!=",'type',1])
								->andWhere(('id!='.$beaconType["id"]))->andWhere(['status' =>1]);
										
						}elseif($beaconType["type"]==2){
							$query->andWhere('type in (3,0,4)') 
								->andWhere(["OR",'parent_id' => $beaconType["id"]])->andWhere(['status' =>1]);
								$alreadyState=true;
												
						}elseif($beaconType["type"]==3){
							$query->andWhere('type in (2,0,4)');
							if($alreadyState==false)							
							$query->andWhere(['id' => $beaconType["parent_id"]])->andWhere(['status' =>1]);
							else
							$query->andWhere(['OR','id' =>$beaconType["parent_id"],'type in (2,0,4)'])->andWhere(['status' =>1]);
							//->orWhere(['type'=>'0']);
								//->andWhere(['OR','id' =>$beaconType["grandparent_id"],'type'=>'0']);	
								
																	
											
						}elseif($beaconType["type"]==0){
							//$query->orWhere('type=0');
														
																	
											
						}
						
					
					
				}
				
				$query->limit(20);
				
				}else{ 
				$query->select('id, group_name AS text')
					->from('tbl_beacon_group')
					->where(['like', 'group_name', $q]) 
					->andwhere(['type' => [0,1]])->andWhere(['status' =>1])               
					->limit(20);
				}	
				
				$command = $query->createCommand();
				$data = $command->queryAll();
			   
				$out['results'] = array_values($data);        
			}
			elseif ($id > 0) {		
				$out['results'] = ['id' => $id, 'text' => Beacongroup::find($id)->group_name];
			}
				return $out;
			}
	
 

    /**
     * Finds the Beaconmanager model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Beaconmanager the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */

html/backend/views/beaconmanager/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\User;
use common\models\Country;
use common\models\Profile;
use common\models\Store;
use backend\models\Beacongroup;
use backend\models\Beaconlocation;
use backend\models\City;
use backend\models\Regions;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use dosamigos\ckeditor\CKEditor;
use yii\web\JsExpression;

$usertype = Yii::$app->user->identity->user_type; 


/* @var $this yii\web\View */
/* @var $model app\models\Beaconmanager */
/* @var $form yii\widgets\ActiveForm */

		/* check for free beacon */
		if($usertype==1){
			if($model->id){
				$storebeaconlist =  ArrayHelper::map(Store::find()
				->joinWith('storebeacons', true, 'LEFT JOIN')
				->select('tbl_store_beacons.beacon_id ,tbl_store_beacons.store_id ,tbl_store.id,tbl_store.storename,tbl_store.status')
				->Where([Store::tableName().'.status'=>1, Store::tableName().'.owner'=> $model->locationOwnerID])
				->andWhere('store_id IS NULL' )
				->orWhere('beacon_id ='.($model->id!=""?$model->id:0))
				->all(), 'id', 'storename');
			
			}else{
				$storebeaconlist = array();
			} 
		}else{
			
			if($model->id){
				$storebeaconlist =  ArrayHelper::map(Store::find()
				->joinWith('storebeacons', true, 'LEFT JOIN')
				->select('tbl_store_beacons.beacon_id ,tbl_store_beacons.store_id ,tbl_store.id,tbl_store.storename,tbl_store.status')
				->andWhere('tbl_store.status=1' )
				->andWhere('tbl_store.owner='.Yii::$app->user->identity->id )
				->andWhere('store_id IS NULL' )
				->orWhere('beacon_id ='.($model->id!=""?$model->id:0))
				->all(), 'id', 'storename'); 
			}else{
				

				$storebeaconlist = array();
			}
		}



?>



    <?php
    $form = ActiveForm::begin([
                'options' => [
                    'id' => 'create-beacon-form',
                    'enctype' =>'multipart/form-data',
                ]
    ]);
    ?>
	 <div class="box-body">
      <div class="form-group">
		
	  <?php // echo $form->errorSummary($model); ?>
	  
		<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
   
		<?= $form->field($model, 'sn')->textInput(['maxlength' => true]) ?>
      
      
		
		<?php 
		
		if($usertype==1){  
			
			$locationOwner =  ArrayHelper::map(User::find()
			->where(['user_type' => 7,'status' => 10])->all(), 'id', 'orgName');  
			echo $form->field($model, 'locationOwnerID')->widget(Select2::classname(), [
			'data' => $locationOwner,
			'options' => ['placeholder' => Yii::t('app','Select Relevant Partner...')],
			'pluginOptions' => [
			'allowClear' => true
			],
		]);
		}else{
			
			$usertype = Yii::$app->user->identity->user_type;
			$userId = $usertype==7?Yii::$app->user->id : Yii::$app->user->identity->advertister_id; ?>
			<?= $form->field($model, 'locationOwnerID')->hiddenInput(['value' =>$userId])->label(false) ?>
			
			<?php $locationOwner =  ArrayHelper::map(User::find()
			->where(['user_type' => 7,'status' => 10,
			'id' => Yii::$app->user->identity->id])->all(), 'id', 'orgName');  
			
		}  
		?>  
		
		<?php 
		?>
		<?php   $locationBrocker =  ArrayHelper::map(Profile::find()->joinWith('user', true, 'INNER JOIN')->select('tbl_users.id ,tbl_users.user_type ,tbl_profile.id ,tbl_profile.user_id, tbl_profile.companyName')->where(['user_type' => 8,'status' => 10 ] )->all(), 'id', 'companyName');
      
		?> 
		
		<?php /*echo $form->field($model, 'locationBrockerID')->widget(Select2::classname(), [
			'data' => $locationBrocker,
			'options' => ['placeholder' => Yii::t('app','Select Brocker...')],
			'pluginOptions' => [
			'allowClear' => true
			],
		]);*/
		?>
		
    
   
     <div class="box box-success">
    <h3>Beacon Location </h3>

		<?= $form->field($model, 'streetAddress')->textInput(['maxlength' => true]) ?>

		<?php   $Countryname =  ArrayHelper::map(Country::find()->all(), 'id_countries', 'name'); ?>
    
		<?= $form->field($model, 'countryID')->dropDownList($Countryname, array('prompt'=>Yii::t('app','Select'))) ?>   
         
     </div>
	 <div class="box box-success">
    <h3>Beacon Parameters</h3>
    
		<?= $form->field($model, 'manufacturer')->textInput(['maxlength' => true]) ?>

		<?= $form->field($model, 'major')->textInput(['maxlength' => true]) ?>

		<?= $form->field($model, 'minor')->textInput(['maxlength' => true]) ?>
		
	
		
		<?= $form->field($model, 'notesBox')->widget(CKEditor::className(), [
				'options' => ['rows' => 6],
				'preset' => 'basic',
				
			]) ?>
			
		
		<?= $form->field($storebeacon, 'store_id')->widget(Select2::classname(), [
			'data' => $storebeaconlist,
			'options' => ['placeholder' => Yii::t('app','Select Store Location ...')],
			'pluginOptions' => [
			'allowClear' => true
			],
		]);
		
		//if(empty($storebeaconlist)) { echo '<div class="help-block">'."Yii::t('app','No Any Free Beacon Device Available.')	".'</div>'; }		
		?>
		
		 <?php
		/*   $data = '';
		   $group_name =  ArrayHelper::map(Beacongroup::find()->orderBy('group_name')->all(), 'id', 'group_name');
			 
		   if(isset($model->groups)) {
			   
			   if(!is_array($model->groups)) {
					$data = explode(',',$model->groups);  
				}else {
					$data =$model->groups; 
				}
			} */
			   
			?>
		
		   <?php   
		   if($model->id){
			   $groups ='';
			   if(is_array($model->groups)){
				 $groups = implode(', ',$model->groups);
				 }else{
				 $groups = $model->groups;
				 }
			 
				$beaconGroup=Beacongroup::find()->where('id IN('.$groups.')')->orderBy('group_name')->asArray()->all();     
				$model->groups =  array_column($beaconGroup,"id");
				$cityDesc= array_column($beaconGroup,"group_name");  
				
			
			}else{
				$cityDesc =array();
			}            
				$url = \yii\helpers\Url::to(['beacon-groupname']);
             ?>
           
  <!-- Assign multiple beacon group-->
<?php
           echo $form->field($model, 'groups')->widget(Select2::classname(), [
           'initValueText' => $cityDesc, // set the initial display text
           'options' => ['placeholder' => 'Search for beacon group ...','multiple' => true],
           'pluginOptions' => [
               'allowClear' => true,
               'minimumInputLength' => 3,
               'language' => [
                   'errorLoading' => new JsExpression("function () { return 'Waiting for results...'; }"),
               ],
               'ajax' => [
                       'url' => $url,
                       'method'=>'POST',
                       'dataType' => 'json',                    
                       'data' => new JsExpression('function(params) { var selectedVal=($("#beaconmanager-groups").val()); return {q:params.term,sq:selectedVal}; }')
                   
               ],
               'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
               'templateResult' => new JsExpression('function(city) { return city.text; }'),
               'templateSelection' => new JsExpression('function (city) { return city.text; }'),
           ],
       ]);
   ?>


     <?= $form->field($model, 'status')->dropDownList(array('' => Yii::t('app','Select'), 1 =>Yii::t('app','Enable'), 0 =>Yii::t('app','Disable') )) ?>
    </div>

   
    </div><!-- /.box-body -->
     <div class="box-footer">

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app','Add Beacon') : Yii::t('app','Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app','Cancel'),  ['index'], ['data-pjax'=>0, 'class'=>'btn btn-default', 'title'=> Yii::t('app','Users')]) ?>
    </div>
     </div>
     

    <?php ActiveForm::end(); ?>

<?php $siteurl = Yii::$app->getUrlManager()->getBaseUrl(); 
	$storelist =$siteurl.'/beaconmanager/storelist'; 
?>   
    
<script type="text/javascript">
	
	$("#beaconmanager-locationownerid").on("change", function () {			
		$('#select2-storebeacons-store_id-container').empty();			
		var values = this.value;	
		
		$.ajax({
			method: "POST",
			url: "<?php echo $storelist; ?>",
			data: { id: values }	
	
	})
	.done(function(result) {
		data1 = JSON.parse(result);	
		
		$('#storebeacons-store_id').empty();	
		 var div_data1="<option value=''><?= Yii::t('app','select') ?></option>";         	
		$.each(data1, function (key, data) {   
			
			$.each(data, function (index, data) {	
						 
				 var div_data="<option value="+index+">"+data+"</option>"; 
					$(div_data1).appendTo('#storebeacons-store_id'); 
					$(div_data).appendTo('#storebeacons-store_id'); 
				
			})
		});
		
	  });
		
	});
var usertype = '<?php echo $usertype ; ?>';
var usertype2 = '<?php echo $model->isNewRecord ; ?>';
if(usertype==7 && usertype2==1 ){	
$(document).ready(function(){
		var values = $("#beaconmanager-locationownerid").val();
	    $.ajax({
			method: "POST",
			url: "<?php echo $storelist; ?>",
			data: { id: values }	
	
	})
	.done(function(result) {
		data1 = JSON.parse(result);	
		
		$('#storebeacons-store_id').empty();	
		 var div_data1="<option value=''><?= Yii::t('app','select') ?></option>";         	
		$.each(data1, function (key, data) {   
			
			$.each(data, function (index, data) {	
						 
				 var div_data="<option value="+index+">"+data+"</option>"; 
					$(div_data1).appendTo('#storebeacons-store_id'); 
					$(div_data).appendTo('#storebeacons-store_id'); 
				
			})
		});
		
	  });
});
}
</script>

html/backend/views/beaconmanager/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BeaconManagerSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="beacon-manager-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'identifier') ?>

    <?= $form->field($model, 'linksUrl') ?>

    <?= $form->field($model, 'majorValue') ?>

    <?php // echo $form->field($model, 'minorValue') ?>

    <?php // echo $form->field($model, 'powerValue') ?>

    <?php // echo $form->field($model, 'rSSIValue') ?>

    <?php // echo $form->field($model, 'soundFileUrl') ?>

    <?php // echo $form->field($model, 'timeStamp') ?>

    <?php // echo $form->field($model, 'interval') ?>

    <?php // echo $form->field($model, 'category') ?>

    <?php // echo $form->field($model, 'groups') ?>

    <?php // echo $form->field($model, 'businessContactNumber') ?>

    <?php // echo $form->field($model, 'businessDetail') ?>

    <?php // echo $form->field($model, 'businessDetailDescription') ?>

    <?php // echo $form->field($model, 'businessEmailAddress') ?>

    <?php // echo $form->field($model, 'businessFacetime') ?>

    <?php // echo $form->field($model, 'businessGalleryCaptions') ?>

    <?php // echo $form->field($model, 'businessGalleryPictures') ?>

    <?php // echo $form->field($model, 'businessLocation') ?>

    <?php // echo $form->field($model, 'beaconCountry') ?>

    <?php // echo $form->field($model, 'businessName') ?>

    <?php // echo $form->field($model, 'businessPictureUrl') ?>

    <?php // echo $form->field($model, 'businessSubscribe') ?>

    <?php // echo $form->field($model, 'businessType') ?>

    <?php // echo $form->field($model, 'businessWebAddress') ?>

    <?php // echo $form->field($model, 'beaconSoundTitle') ?>

    <?php // echo $form->field($model, 'passID') ?>

    <?php // echo $form->field($model, 'passUrl') ?>

    <?php // echo $form->field($model, 'locationOwnerID') ?>

    <?php // echo $form->field($model, 'locationBrockerID') ?>

    <?php // echo $form->field($model, 'locationID') ?>

    <?php // echo $form->field($model, 'streetNumber') ?>

    <?php // echo $form->field($model, 'streetAddress') ?>

    <?php // echo $form->field($model, 'countryID') ?>

    <?php // echo $form->field($model, 'cityID') ?>

    <?php // echo $form->field($model, 'suburbID') ?>

    <?php // echo $form->field($model, 'postCode') ?>

    <?php // echo $form->field($model, 'latitude') ?>

    <?php // echo $form->field($model, 'longitude') ?>

    <?php // echo $form->field($model, 'imgBeaconLoc') ?>

    <?php // echo $form->field($model, 'manufacturer') ?>

    <?php // echo $form->field($model, 'manufacturerSerial') ?>

    <?php // echo $form->field($model, 'uuid') ?>

    <?php // echo $form->field($model, 'major') ?>

    <?php // echo $form->field($model, 'minor') ?>

    <?php // echo $form->field($model, 'rssiID') ?>

    <?php // echo $form->field($model, 'intervalID') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app','Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app','Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

html/backend/views/beaconmanager/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Beaconmanager */

$this->title = Yii::t('app','Add a New Beacon');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app','Beacon Manager'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>


<section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- general form elements -->
              <div class=" panel panel-primary">
                <div class="panel-heading">    
                    <div class="pull-right">                       
                    </div>
                    <!-- Header Title-->
                    <h3 class="panel-title">
                        <i class="glyphicon glyphicon-plus"></i>  <?= Html::encode($this->title) ?>
                    </h3>
                    <!-- Header Title end -->
                    <div class="clearfix"></div>
                </div>
                
                <div class="panel-before" >    
                <div class="pull-right">
        <div role="toolbar" class="btn-toolbar kv-grid-toolbar">
            <div class="btn-group"><a title="<?= Yii::t('app','All Beacon Manager') ?>" href="<?=Yii::$app->urlManager->createUrl(['beaconmanager/index',])?>" class="btn btn-primary"><i class="fa fa-gears"></i></a> 
            <a data-pjax="0" title="<?= Yii::t('app','Reset Grid') ?>" href="<?=Yii::$app->urlManager->createUrl(['beaconmanager/create',])?>" class="btn btn-default"><i class="glyphicon glyphicon-repeat"></i></a></div>


        </div>    
    </div>
    
    <div class="clearfix"></div></div>
                
                
                <!-- form start -->
                
                 <?= $this->render('_form', [
        'model' => $model,
        'storebeacon'=>$storebeacon,
    ]) ?>
              
              </div><!-- /.box -->
            </div><!--/.col (right) -->
          </div>   <!-- /.row -->
        </section>

html/backend/views/beaconmanager/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Beaconmanager */

$this->title = Yii::t('app','Update Beacon: ') . ' ' . ucfirst($model->name);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app','Beacon Manager'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => ucfirst($model->name), 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app','Update');
?>
    <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- general form elements -->
               <div class=" panel panel-primary">
                <div class="panel-heading">    
                    <div class="pull-right">                       
                    </div>
                    <!-- Header Title-->
                    <h3 class="panel-title">
                        <i class="fa fa-gears"></i>  <?= Html::encode($this->title) ?>
                    </h3>
                    <!-- Header Title end -->
                    <div class="clearfix"></div>
                </div>
                <!-- form start -->
                
                 <?= $this->render('_form', [
        'model' => $model,
        'storebeacon'=>$storebeacon,
        'storeBeaconModel'=>$storeBeaconModel,
    ]) ?>
              
              </div><!-- /.box -->
            </div><!--/.col (right) -->
          </div>   <!-- /.row -->