html/common/models/Auction.php
<?php
namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Query;
use yii\behaviors\SluggableBehavior;
use yii\behaviors\BlameableBehavior;
use common\models\Country;
use common\models\States;
use api\modules\v1\models\Agency;
use api\modules\v1\models\Agent;
use api\modules\v1\models\ApplyBid;

/**
 * This is the model class for table "tbl_properties".
 *
 *
 */
class Auction extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%auction_event}}';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['listing_id', 'auction_type', 'datetime_start', 'datetime_expire', 'starting_price', 'estate_agent_id', 'auction_currency_id', 'auction_bidding_status'], 'required' ,'on'=>'adminUpdate'],
        	[['listing_id', 'auction_type', 'date', 'time', 'datetime_start', 'datetime_expire', 'starting_price', 'home_phone_number', 'estate_agent', 'picture_of_listing', 'duration', 'real_estate_active_himself', 'real_estate_active_bidders', 'reference_relevant_electronic', 'reference_relevant_bidder', 'created_at', 'auction_status', 'streaming_url', 'streaming_status', 'templateId', 'envelopeId', 'documentId', 'document', 'recipientId', 'bidding_status', 'updated_at', 'created_by', 'updated_by', 'estate_agent_id', 'agency_id', 'auction_currency_id', 'auction_bidding_status'], 'safe'],
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
			'id' => Yii::t('app','Id'),
			'listing_id' => Yii::t('app','Property'),
			'datetime_start' => Yii::t('app','Auction Start Time'),
			'datetime_expire' => Yii::t('app','Auction End Time'),
			'duration' => Yii::t('app','Auction Duration'),
        ];
    }

    /**
     * @inheritdoc
     */   
   	public function beforeSave($insert)
	{
        //echo '<pre>'; print_r($this); die('herse');
		if(!empty($this->auction_type)){
			if($this->auction_type == 'auction')
				$this->auction_status = 1;
			else if($this->auction_type == 'streaming')
				$this->auction_status = 2;
			else
				$this->auction_status = 3;
		}
		if(strstr($this->datetime_start,"-")){
			$this->datetime_start = strtotime($this->date.' '.$this->time);
		}
		if(strstr($this->date,"-") && !empty($this->date))
		{          
			$this->date=strtotime($this->date);
		}
		/*if(!empty($this->document))
			$this->document = json_encode($this->document);*/
	    if (! parent::beforeSave($insert)) {
	    	return false;
	    }

    //	$this->updated_by= Yii::$app->user->id;
    	$this->updated_at= time();
		if ($insert) {			    		
    //		$this->created_by= Yii::$app->user->id;
			$this->created_at= time();
     	}
    	return true;
	    
	}
	
	public function afterFind()
	{
		parent::afterFind();
		
		/* Date From */
		if(!strstr($this->date,"-") && !empty($this->date))
		{             
			$this->date=date("Y-m-d",$this->date);
		}						
		if(!strstr($this->datetime_start,"-") && !empty($this->datetime_start))
		{             
			$this->datetime_start=date("Y-m-d H:i:s",$this->datetime_start);
		}						
		if(!strstr($this->updated_at,"-") && !empty($this->updated_at))
		{             
			$this->updated_at=date("Y-m-d",$this->updated_at);
		}	
		//~ if(!empty($this->document)){
			//~ $documents = json_decode($this->document);
			//~ $details = [];
			//~ $link = Yii::$app->urlManagerFrontEnd->createAbsoluteUrl('images/property/doc');
			//~ //$object = new \stdClass();
			//~ if(count($documents)>1){
				//~ foreach($documents as $key => $document){
					//~ if(!empty($document))
					//~ $data['url'] = $document;
					//~ $details[] = $data;
					//~ }
					//~ //print_r((object)$details);die;
					//~ $this->document = $details;
			//~ }elseif(count($documents) == 1){
				//~ $data['url'] = $documents[0];
				//~ $details[] = $data;
				//~ $this->document = $details;
			//~ }
		//~ }					
		return true;		
	}
	
	public function getCountry()
	{
		return $this->hasOne(Country::className(), ['id_countries' =>'country_id']); 
	}
		
	public function getState()
	{
		return $this->hasOne(States::className(), ['id' =>'state']); 
	}
    
    public function getAgency() 
    {
    	return $this->hasOne(Agency::className(), ['id' =>'agency_id']);
    }
    
    public function getAgent() 
    {
    	return $this->hasOne(Agent::className(), ['id' =>'estate_agent_id']);
    }
    
	public function fields(){
        $fields = parent::fields();
		$fields['agent'] = function ($model) {
			return $model->agent;
		};
		$fields['agency'] = function ($model) {
			return $model->agency;
		};        
	   return $fields;
	}
		
	/*public function extraFields()
	{
		return [
		'addresstype',//=>['id','passUrl']
		

		];
	}*/
	
	public function getPropertylive()
    {
         return $this->hasOne(Property::className(), ['id' => 'listing_id']);
    }
    
    public static function checkvalidBidder($auction_id){
		/* User Type = 3 Customer/Bidder , 10 Agent */
		
		$userType = (isset(Yii::$app->User->identity->user_type)?Yii::$app->User->identity->user_type:0);
		$userID = (isset(Yii::$app->User->id)?Yii::$app->User->id:0);
		
			 
			//if(($userType>0) && ($userID>0)) {
			$checkvalidBid = ApplyBid::findOne(['user_id' => $userID,'auction_id'=>$auction_id]);
			  $checkvalidBidInEvent = self::findOne(['auction_id'=>$auction_id]);
			  if(($checkvalidBidInEvent  && in_array($userID,explode(",",$checkvalidBidInEvent->reference_relevant_bidder)))||($checkvalidBid))
			  {
				  
				  $checkvalidBid=true;
			  }
			  if($checkvalidBid)				 
					 return 1;					
					else 
					return 13;
			/* Check bidder user type */
			 if($userType==2 || $userType==6){
				    if($userType==2){
						$property=Property::find()->where(['id'=>$auction_id])->andWhere(["OR",['estate_agent_id' => $userID],['second_agent_id' => $userID]])->one();
						if(!empty($property))
						return 10;	
						else
						return 11;				
					}
					return $userType;
			  }else{
				return 0;
			  }
			
			
			//}return 0;		
	
	
	}
    
    // Function to get the detail of an Auction
    public function getAuctionDetail($id){
        return $this->findOne(['id' => $id]);
    }
    
    // To Get the Agent Id by auction_id
	public function getAgentId($auction_id){ 
        return $query = Auction::find(['id'=>$auction_id])->select('estate_agent_id')->one();
	}

}

html/backend/controllers/AuctionsController.php
<?php
namespace backend\controllers;
use Yii;
use common\models\Auction;
use common\models\AuctionSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use yii\imagine\Image;
use Imagine\Image\Box;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class AuctionsController extends Controller
{
    /*public function behaviors()
    {
        $behaviors['access'] = [
            'class' => AccessControl::className(),
            'rules' => [
                [                       
                   'allow' => true,
                   'roles' => ['@'],
                   'matchCallback' => function ($rule, $action) {
                        $module = Yii::$app->controller->module->id;                     
                        $action = Yii::$app->controller->action->id;                         
                        $controller = Yii::$app	->controller->id;                        
                        $route = "$controller/$action";                                                    	
                        $post = Yii::$app->request->post();
//                        if(\Yii::$app->user->can($route)){
//                            return true;
//                        }
                    } 
                ],
            ],
        ];
        return $behaviors;
	}*/

    /**
     * Lists all Cardtype models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AuctionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Cardtype model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Cardtype model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate(){
        $model = new Auction();
        //$model->scenario = 'create';
        $model->scenario = "adminUpdate";
		if($model->load(Yii::$app->request->post()) ){
            $posted = Yii::$app->request->post();
          echo   strtotime($posted['Auction']['datetime_start']);
        echo '<pre>'; print_r(Yii::$app->request->post()); die('he');
		//if($model->load(Yii::$app->request->post()) && ($model->imageFile = UploadedFile::getInstance($model,'imageFile'))	&& $model->save()){
            /*if(isset($model->imageFile)) {
                //echo $model->imageFile = UploadedFile::getInstance($model, 'imageFile'); die();
                $uniqueimage = substr(md5(date("Ymdhis")),0,15); 
                // save image in user model 
                if ($model->imageFile) {
                    $imageName = $uniqueimage;
                    $model->icon = $imageName.'.'.$model->imageFile->extension;
                    $model->imageFile->saveAs(Yii::$app->params['icons'].'/'.$imageName.'.'.$model->imageFile->extension);
                    Image::getImagine()->open(Yii::$app->params['icons'].'/'.$model->icon)->thumbnail(new Box(300,300))->save(Yii::$app->params['icons'].'/'.$model->icon	); 
                }
            }*/
            $model->save(false); 
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Cardtype model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model->scenario = "adminUpdate";
       // ECHO '<PRE>'; PRINT_R(Yii::$app->request->post());
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			
        	  /*save image in user model */ 
 			/* get old file name */
// 			$model->setAttribute(Yii::$app->request->post());
//            echo '<pre>'; print_r($model); die('jher');
            $model->save(false);
			    	
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
	
	
	/*Delete by ajax */
	
	public function actionDeletebyajax()  
	{
		$pid = $_POST['id'];  
		if($pid) {
			$this->findModel($pid)->delete();
			echo $pid; exit;
		}
	}
	
    /**
     * Deletes an existing Cardtype model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Cardtype model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Cardtype the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function findModel($id)
    {
        if (($model = Auction::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

html/backend/views/auctions/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\Property;
use common\models\CommonModel;
//use kartik\daterange\DateRangePicker;
use kartik\datetime\DateTimePicker;

/*use yii\bootstrap\Modal;
//use kartik\widgets\ActiveForm;
use kartik\widgets\DateTimePicker;*/
/* @var $this yii\web\View */
/* @var $model common\models\cardtype */
/* @var $form yii\widgets\ActiveForm */
?>
    <?php
    $form = ActiveForm::begin([
        'options' => [
            'id' => 'create-cardtype-form',
            'enctype' =>'multipart/form-data',
        ]
    ]);
    ?>
    <?php // echo $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
    <?php // echo $form->field($model, 'desc')->textArea(['maxlength' => 500, 'rows' => 6, 'cols' => 50]) ?>
    <div class="box-body">
        <div class="row">
            <div class="col-md-6">
                <?php echo $form->field($model, 'listing_id')->dropDownList(Property::getActiveProperties(),['class'=>'form-control', 'prompt'=>'Choose Option']); ?>
            </div>
            <div class="col-md-6">
                <?php //echo $form->field($model, 'auction_type')->dropDownList(CommonModel::getAuctionType(),['class'=>'form-control', 'prompt'=>'Choose Option']); ?>
                <?php echo $form->field($model, 'estate_agent_id')->dropDownList(CommonModel::getActiveAgents(),['class'=>'form-control', 'prompt'=>'Choose Option']); ?>                
            </div>
        </div>        
        <div class="row">
            <div class="col-md-6">
                <?php echo $form->field($model, 'auction_currency_id')->dropDownList(CommonModel::getCurrency(),['class'=>'form-control', 'prompt'=>'Choose Option']); ?>
            </div>
            <div class="col-md-6">
                <?php echo $form->field($model, 'starting_price'); ?>
            </div>
        </div>        
        <div class="row">
            <div class="col-md-6">
                <?php //echo $form->field($model, 'datetime_start'); ?>
                <?php 
                    echo $form->field($model, 'datetime_start')->widget(DateTimePicker::classname(), [
                    'options' => ['placeholder' => 'Enter Start Date & Time'],
                    'readonly'  => true,
                    'pluginOptions' => [
                        'autoclose' => true
                    ]
                ]);?>                
            </div>
            <div class="col-md-6">
                <?php 
                    echo $form->field($model, 'datetime_expire')->widget(DateTimePicker::classname(), [
                    'options' => ['placeholder' => 'Enter Start Date & Time'],
                    'readonly'  => true,
                    'pluginOptions' => [
                        'autoclose' => true,
                       // 'startDate'=> date('d-m-Y')
                    ]
                ]);?>                 
                <?php //echo $form->field($model, 'datetime_expire'); ?>
            </div>
        </div>        
        <div class="row">
            <div class="col-md-6">
                <?php echo $form->field($model, 'duration')->textInput(['maxlength' => 2, 'class' => 'numericInput form-control' ])->label('Auction duration (in Minutes) Numeric'); ?>
            </div>
            <div class="col-md-6">
                <?php echo $form->field($model, 'auction_bidding_status')->dropDownList(CommonModel::getBiddingStatus(),['class'=>'form-control', 'prompt'=>'Choose Option']); ?>                
                <?php //echo $form->field($model, 'auction_bidding_status')->dropDownList(['1' => 'No Online Bidding', '2' => 'Online Bidding', '3' => 'Offsite Bidding'],['prompt'=>'Choose Option']); ?>
            </div>
        </div>        
        <div class="box-footer">
            <div class="form-group">
                <?= Html::submitButton($model->isNewRecord ? Yii::t('app','Create') : Yii::t('app','Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
                <?= Html::a(Yii::t('app','Cancel'),  ['index'], ['data-pjax'=>0, 'class'=>'btn btn-default', 'title'=> Yii::t('app','Users')]) ?>
            </div>
        </div>
    </div>

    <!-- /.box-body -->
<?php ActiveForm::end(); ?>

html/backend/views/auctions/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\CardtypeSeach */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="cardtype-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'icon') ?>

    <?= $form->field($model, 'status') ?>

    <?= $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app','Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app','Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

html/backend/views/auctions/create.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
/* @var $model app\models\Region */

$this->title = Yii::t('app', 'Create Auction');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app','Auctions'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <!-- general form elements -->
            <div class=" panel panel-primary">
                <div class="panel-heading">
                    <div class="pull-right">
                    </div>
                    <!-- Header Title-->
                    <h3 class="panel-title">
                        <i class="glyphicon glyphicon-plus"></i>
                        <?= Html::encode($this->title) ?>
                    </h3>
                    <!-- Header Title end -->
                    <div class="clearfix"></div>
                </div>
                <div class="panel-before">
                    <div class="pull-right">
                        <div role="toolbar" class="btn-toolbar kv-grid-toolbar">
                            <div class="btn-group">
                                <a title="<?= Yii::t('app','All Auctions') ?>" href="<?=Yii::$app->urlManager->createUrl(['auctions/index',])?>" class="btn btn-primary"><i class="fa fa-indent"></i></a>
                                <a data-pjax="0" title="<?= Yii::t('app','Reset Grid') ?>" href="<?=Yii::$app->urlManager->createUrl(['auctions/create',])?>" class="btn btn-default"><i class="glyphicon glyphicon-repeat"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <!-- form start -->
                <?= $this->render('_form', ['model' => $model]) ?>
            </div>
            <!-- /.box -->
        </div>
        <!--/.col (right) -->
    </div>
    <!-- /.row -->
</section>

html/backend/views/auctions/index.php
<?php
use yii\helpers\Html;
use kartik\grid\GridView;
use common\models\CommonModel;
/* @var $this yii\web\View */
/* @var $searchModel common\models\CardtypeSeach */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Auction List';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="cardtype-index">
<?php //echo $form->field($model, 'auction_currency_id')->dropDownList(CommonModel::getCurrency(),['class'=>'form-control', 'prompt'=>'Choose Option']); ?>
<?php
    echo GridView::widget([
        'dataProvider'=>$dataProvider,
        'filterModel'=>$searchModel,
        'rowOptions' => function ($model, $key, $index, $grid) {
        return ['id' => $model['id']];
        },
        'columns' => [
            'id',
            'listing_id',
            /*[
                'attribute' => 'auction_type',
                'value'=> 'auction_type',
               // 'format' => 'raw', 
                'filter' => CommonModel::getAuctionType(),
            ],*/            
            [
                'attribute'=>'auction_bidding_status',
                'value'=>'auction_bidding_status',
                'format' => 'raw', 
                'filter' => CommonModel::getBiddingStatus(),
            ],            
            'starting_price',
           // 'auction_bidding_status',
           // ['attribute'=>'owner_id', 'filter'=>CommonModel::getOwnerList($userModel,['status'=>1, 'role'=>[11,12]],['_id', 'name', 'firstname', 'lastname'])],            
//            ['attribute' => 'auction_currency_id', 'value' => CommonModel::getCurrencyData(6), 'format' => 'raw', 'filter' => CommonModel::getCurrency()],
            //['attribute' => 'auction_currency_id', 'value' => CommonModel::getCurrencyData(6), 'format' => 'raw', 'filter' => CommonModel::getCurrency()],
            //'name',
            /*[
                'attribute'=>'listing_id',
                'value'=>'listing_id',
                'format' => 'raw', 
                'filter' => array('1' => Yii::t('app','Enable'), '0' => Yii::t('app','Disable') ),
            ],*/
            // 'updated_at',
            ['class'=>'kartik\grid\ActionColumn'],
        ],
        'containerOptions' => ['style'=>'overflow: auto'], // only set when $responsive = false
        'headerRowOptions' => ['class'=>'kartik-sheet-style'],
        'filterRowOptions' => ['class'=>'kartik-sheet-style'],
        'pjax'=>true, // pjax is set to always true for this demo
        //   'export'=>false,       
        'beforeHeader'=>[
            [
                /*'columns'=>[
                ['content'=>'Header Before 1', 'options'=>['colspan'=>5, 'class'=>'text-center warning']], 
                ['content'=>'Header Before 2', 'options'=>['colspan'=>3, 'class'=>'text-center warning']], 
                ['content'=>'Header Before 3', 'options'=>['colspan'=>3, 'class'=>'text-center warning']], 
                ],*/
                'options'=>['class'=>'skip-export'] // remove this row from export
            ]
        ],
        // set your toolbar
        'toolbar'=> [
            ['content'=>
            Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'],[ 'title'=>Yii::t('app','Add Auction'),'data-pjax'=>1, 'class'=>'btn btn-success', ]) . ' '.
            Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], ['data-pjax'=>0, 'class'=>'btn btn-default', 'title'=> Yii::t('app','Reset Grid')])
            ],
            '{export}',
            '{toggleData}',
        ],
        // set export properties
        'export'=>[
            'fontAwesome'=>true
        ],
        // parameters from the demo form
        'bordered'=>true,
        'striped'=>false,
        'condensed'=>true,
        'responsive'=>true,
        'hover'=>true,
        'showPageSummary'=>true,
        'responsiveWrap' => false,
        'panel'=>[
            'type'=>GridView::TYPE_PRIMARY,
            'heading'=>'<i class="fa fa-indent"></i> '.Yii::t('app','Auctions List'),
        ],
        'persistResize'=>false,
        'exportConfig'=>['csv'=>'csv'],
    ]);?>
</div>

html/backend/views/auctions/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Cardtype */

$this->title = Yii::t('app','Update Auction: ') . ' ' . ucfirst($model->id);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app','Auction'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Yii::t('app','Update');
$this->params['breadcrumbs'][] = ['label' => ucfirst($model->id), 'url' => ['view', 'id' => $model->id]];
?>
    <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- general form elements -->
               <div class=" panel panel-primary">
                <div class="panel-heading">    
                    <div class="pull-right">                       
                    </div>
                    <!-- Header Title-->
                    <h3 class="panel-title">
                        <i class="fa fa-indent"></i>  <?= Html::encode($this->title) ?>
                    </h3>
                    <!-- Header Title end -->
                    <div class="clearfix"></div>
                </div>
                <!-- form start -->
                
                 <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
              
              </div><!-- /.box -->
            </div><!--/.col (right) -->
          </div>   <!-- /.row -->

html/backend/views/auctions/view.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
$this->title = Yii::t('app','View Auction Detail: ') . ' ' .ucfirst($model->id);
$this->params['breadcrumbs'][] = ['label' => Yii::t('app','Cardtypes'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <!-- left column -->
    <div class="col-md-12">
        <div class=" panel panel-primary">
            <div class="panel-heading">
                <div class="pull-right">
                </div>
                <!-- Header Title-->
                <h3 class="panel-title">
                    <i class="fa fa-indent"></i>
                    <?= Html::encode($this->title) ?>
                </h3>
                <!-- Header Title end -->
                <div class="clearfix"></div>
            </div>
            <!-- general form elements -->
            <div class="box-header with-border">
                <h3 class="box-title">
                    <!--<?= Html::encode($this->title) ?>-->
                </h3>
                <p>
                    <?= Html::a(Yii::t('app','Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
                    <?= Html::a(Yii::t('app','Delete'), ['delete', 'id' => $model->id], [
                        'class' => 'btn btn-danger',
                        'data' => [
                            'confirm' => Yii::t('app','Are you sure you want to delete this item?'),
                            'method' => 'post',
                        ],
                    ]) ?>
                    <?= Html::a(Yii::t('app','Cancel'), ['index', 'id' => $model->id], ['class' => 'btn bg-green']) ?>
                </p>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <div class="table-responsive">
                <?= DetailView::widget([
                    'model' => $model,
                    'attributes' => [
                        'id',
                        'listing_id',
                        /*[
                            'attribute'=>'icon',
                            'value'=> $model->icon,
                            'format' => ['image',['width'=>'100','height'=>'70']],
                        ],*/
                        /*[                     
                            'label' => Yii::t('app','Status'),
                            'value' => $model->statustype,
                        ],*/
                        [                     
                            'label' => Yii::t('app','Created At'),
                            'value' => $model->created_at,
                        ],
                        [                     
                            'label' => Yii::t('app','Updated at'),
                            //'value' => date("D, d M Y H:i:s",$model->updated_at),
                            'value' => $model->updated_at,
                        ],
                    ],
                ]) ?>
            </div>
        </div>
        <!-- /.box -->
    </div>
    <!--/.col (right) -->
</div>
<!-- /.row -->